services:

  web:
      build:
        context: ./app
        dockerfile: ${NODE_ENV:-development}.Dockerfile
      ports:
        - "${PORT:-8080}:3000"
      volumes:
        - ./app:/app
        - /app/node_modules
        - /app/.next
      environment:
        - NODE_ENV=${NODE_ENV:-development}
        - NEXT_PUBLIC_SANITY_PROJECT_ID=${NEXT_PUBLIC_SANITY_PROJECT_ID:-r9iqr1x2}
        - NEXT_PUBLIC_SANITY_DATASET=${NEXT_PUBLIC_SANITY_DATASET:-production}
        - NEXT_PUBLIC_SANITY_DATASET_DEV=${NEXT_PUBLIC_SANITY_DATASET_DEV:-development}
        - SANITY_API_VERSION=${SANITY_API_VERSION:-2024-03-21}
        # - NEXT_PUBLIC_GA_ID=${NEXT_PUBLIC_GA_ID:<fallback ID>}
        - WATCHPACK_POLLING=true
      restart: unless-stopped
      
